### ISSUE TITLE
App does not display an error if sign-in with Google fails

### ISSUE THREAD

**Issue by vincentmvdm** [pizza442/BeatTheLag#20] opened 2019-06-11 21:40 UTC
The app uses sign in with Google for authentication. However, if for whatever reason the sign in fails on Google's end, the app doesn't notify the user. In other words, the app is not listening for errors produced by Firebase's Google's Auth.

Steps to reproduce:

1. Go to the app and click "Sign in with Google"
2. Cancel out the flow and notice how no error is displayed on the home page
3. If the app was listening for errors with Google authentication, even an error as simple as the user manually cancelling the sign-in process would be communicated back to the home page and shown there

**Comment by sKhan16** [comment] 2019-06-12 18:20
Thanks for showing us this bug! However, we haven't been able to reproduce this bug because we're not sure what you mean by canceling the flow, if sign in fails on googles end, they tell you that the sign in has failed and allowed you to re-enter your account information. Would you mind clarifying what you meant by canceling out the flow so we can reproduce the bug that you ran into?

**Comment by VanelyRuiz** [comment] 2019-06-12 21:36
Fixed in commit: https://github.com/pizza442/BeatTheLag/commit/f54ed2da2c05364e82fc336a416b9a6226269b9c

Unfortunately, we were unable to reproduce your exact error; however, we handled the errors that occur when getting redirected in the sign in process and signing out. These errors will now be displayed to the user below our app description.

**Closed as completed by VanelyRuiz** 2019-06-12 21:36 UTC
Labels: bug, google
